matrix:
  include:
    - env: ver=1.0.0
    - env: ver=0.21.0

os: linux-ppc64le
dist: xenial
sudo: required
services:
  - docker

language: go

go:
  - 1.9.4

install:   
  - sudo apt-get update
  - sudo apt-get install -y lftp
  - python3 ftp_version.py

script:
  - bash build.sh
