matrix:
  include:
    - env: ver=1.0.5
    - env: ver=1.3.1
    - env: ver=1.0.4
    - env: ver=1.3.0
    - env: ver=1.0.3
    - env: ver=1.0.2
    - env: ver=1.0.1
    - env: ver=1.2.0
    - env: ver=1.1.0

os: linux-ppc64le
dist: xenial
sudo: required
services:
  - docker

language: go

go:
  - 1.9.4

install:   
  - sudo apt-get update
  - sudo apt-get install -y lftp
  - python3 ftp_version.py

script:
  - bash build.sh
