sudo: required

os: 
  - linux-ppc64le
  
services:
- docker

language: go

go:
- 1.9.4

before_script:
  - pwd
  - ls
  - cd $GOPATH/src/github.com
  - mkdir kiali
  - cd kiali
  - wget https://github.com/kiali/kiali/archive/v0.16.2.zip
  - unzip v0.16.2.zip
  - mv -r v0.16.2 kiali
  - cd kiali 
  - rm Makefile
  - mv /home/travis/gopath/src/github.com/Unicamp-OpenPower/kiali-releases/Makefile $GOPATH/src/github.com/kiali/kiali/Makefile
 
install:   
 - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/glide/glide-0.13.1
 - mv glide-0.13.1 glide
 - sudo chmod 755 glide
 - sudo mv glide /usr/bin/glide
 - glide

script:
  - ls
  - make build
  - make test
  - ls
  - cd $GOPATH/bin
  - ls
  - sudo chmod 777 kiali
  - ./kiali
