os: linux-ppc64le
dist: xenial
sudo: required
services:
  - docker

language: go

go:
  - 1.9.4

install:   
  - sudo apt-get update
  - sudo apt-get install -y lftp
  - alias python=/usr/local/bin/python3
  - python ftp_version.py

script:
  - bash build.sh
