os: linux
arch: ppc64le
dist: bionic
language: go
sudo: required
#services:
#  - docker

go: 1.13.x

install:   
  - sudo apt-get update
  - sudo apt-get install -y lftp
  - python3 ftp_version.py

script:
  - bash build.sh
